server:
  port: 9527
    
spring: 
   application:
    name: microservicecloud-zuul-gateway
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com     #实列id
    prefer-ip-address: true
zuul: 
  #访问公共前缀
  prefix: /yangzhengxing
  ignored-services: "*"  #microservicecloud-dept表示：忽略微服务id为microservicecloud-dept的微服务，使得http://myzuul.com:9527/microservicecloud-dept/dept/get/1不能访问，#只能通过http://myzuul.com:9527/mydept/dept/get/1这个访问呢！;#"*"表示：批量忽略微服务，即忽略所有微服务，推荐使用
  routes: 
    mydept123.serviceId: microservicecloud-dept #将id为microservicecloud-dept的微服务路径映射为 /mydept/**，列子：http://myzuul.com:9527/microservicecloud-dept/dept/get/1映射成http://myzuul.com:9527/mydept/dept/get/1
    mydept123.path: /mydept/**

info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  
  
  
  
  
  
  
  
  
  
  
  
  